ex_site_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, registration_view, logout_view
from contact.views import contact_list, contact_close


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', login_view, name='login'),
    path('registration/', registration_view, name='registration'),
    path('logout/', logout_view, name='logout'),

    path('', include('main_page.urls')),
    path('manager/', include('manager.urls'), name='manager'),
    path('manager/contact/', contact_list, name='contact_list'),
    path('update/<int:pk>/', contact_close, name='contact_close'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path, include
from .views import reservation_list, reservation_close

app_name = 'manager'


urlpatterns = [
    path('', reservation_list, name='reservation_list'),
    path('update/<int:pk>/', reservation_close, name='reservation_close'),
]

manager/models.py
from django.db import models
from django.core.validators import RegexValidator


class UserReservation(models.Model):
    mobile_phone_re = RegexValidator(regex=r'(^\+38)?(-|\s)?(\d{3})(-|\s)?(\d{3})(-|\s)?(\d{2})(-|\s)?(\d{2})',
                                     message='Некоректно введено номер телефону.')
    name = models.CharField(max_length=50)
    num_people = models.SmallIntegerField()
    phone = models.CharField(max_length=20, validators=[mobile_phone_re])
    message = models.TextField(max_length=500, blank=True)

    is_processed = models.BooleanField(default=False)
    data_in = models.DateTimeField(auto_now_add=True)
    date_modify = models.DateTimeField(auto_now=True)

    class Meta:

        ordering = ('-data_in', )

    def __str__(self):
        return f'{self.name}: {self.phone}: {self.message}'

manager/views.py
from django.shortcuts import render, redirect
from .models import UserReservation
from django.contrib.auth.decorators import login_required, user_passes_test


def is_manager(user):
    return user.groups.filter(name='manager').exists()


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservation_list(request):
    reservations = UserReservation.objects.filter(is_processed=False)
    return render(request, 'reserve_list.html', context={'reserve_list': reservations})


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservation_close(request, pk):
    UserReservation.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservation_list')

manager/templates/reserve_list.html
{% extends 'index.html' %}

{% block content %}
    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in reserve_list %}
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% url 'manager:reservation_close' pk=item.pk %}">
                                <button type="button" class="btn btn-primary">Close request</button>
                            </a>
                        </div>
                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.phone }}</div>
                        <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}