ex_site_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, registration_view, logout_view
from contact.views import contact_list, contact_close


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', login_view, name='login'),
    path('registration/', registration_view, name='registration'),
    path('logout/', logout_view, name='logout'),

    path('', include('main_page.urls')),
    path('manager/', include('manager.urls'), name='manager'),
    path('manager/contact/', contact_list, name='contact_list'),
    path('update/<int:pk>/', contact_close, name='contact_close'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path, include
from .views import reservation_list, reservation_close

app_name = 'manager'


urlpatterns = [
    path('', reservation_list, name='reservation_list'),
    path('update/<int:pk>/', reservation_close, name='reservation_close'),
]

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Yummy Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/main.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Yummy - v1.2.1
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>Якась назва<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/#hero">Головна</a></li>
          <li><a href="/#about">Про Нас</a></li>
          <li><a href="/#menu">Меню</a></li>
          <li><a href="/#events">Заходи</a></li>
          <li><a href="/#chefs">Шеф-Кухарі</a></li>
          <li><a href="/#gallery">Галерея</a></li>
          {% if 'manager' in user.groups.all.0.name %}
            <li><a href="{% url 'manager:reservation_list' %}">Менеджер</a></li>
          {% endif %}
          <li><a href="/#contact">Контакти</a></li>
        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="/#book-a-table">Забронювати</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section href="index.html" id="hero" class="hero d-flex align-items-center section-bg">
    <div class="container">
      <div class="row justify-content-between gy-5">
        <div class="col-lg-5 order-2 order-lg-1 d-flex flex-column justify-content-center align-items-center
         align-items-lg-start text-center text-lg-start">
          <h2 data-aos="fade-up">Насолоджуйтесь <br>Смачною Їжею</h2>
          <p data-aos="fade-up" data-aos-delay="100">Щось написано...</p>
          <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
            <a href="/#book-a-table" class="btn-book-a-table">Забронювати Столик</a>
            <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox btn-watch-video
            d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Дивитися Відео</span></a>
          </div>
        </div>
        <div class="col-lg-5 order-1 order-lg-2 text-center text-lg-start">
          <img src={% static "assets/img/hero-img.png" %} class="img-fluid" alt="" data-aos="zoom-out"
               data-aos-delay="300">
        </div>
      </div>
    </div>
  </section><!-- End Hero Section -->

  <main href="index.html" id="main">

    {% block content %}

    {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer href="index.html" id="footer" class="footer">
    {% for item in footer %}
        <div class="container">
          <div class="row gy-3">
            <div class="col-lg-3 col-md-6 d-flex">
              <i class="bi bi-geo-alt icon"></i>
              <div>
                <h4>Адреса</h4>
                <p>
                  {{ item.address }} {{ item.name_city }}<br>
                  {{ item.name_city }}<br>
                </p>
              </div>

            </div>


            <div class="col-lg-3 col-md-6 footer-links d-flex">
              <i class="bi bi-telephone icon"></i>
              <div>
                <h4>Резервація</h4>
                <p>
                  <strong>Телефон:</strong> {{ item.phone_num }}<br>
                  <strong>Пошта:</strong> {{ item.email }}<br>
                </p>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
              <i class="bi bi-clock icon"></i>
              <div>
                <h4>Час Роботи</h4>
                <p>
                  <strong>{{ item.work_time }}</strong><br>
                  {{ item.close_time}}
                </p>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Підписуйтесь на Нас</h4>
              <div class="social-links d-flex">
                <a href="/#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="/#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="/#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="/#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>

          </div>
        </div>
    {% endfor %}
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="/#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

</body>

</html>